name: Deploy to Hugging Face Space

# Script ini akan berjalan otomatis setiap ada "git push" ke branch "main"
on:
  push:
    branches: [ main ]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # Penting jika model Anda menggunakan Git LFS di GitHub

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Hapus riwayat Git lama di runner agar Hugging Face tidak membaca commit yang bermasalah
          rm -rf .git
          
          # 2. Buat riwayat Git baru yang bersih khusus untuk Hugging Face
          git init
          git branch -M main
          
          # 3. Setup Git LFS dan pastikan file model ditaruh di LFS untuk Hugging Face
          git lfs install
          git lfs track "*.pt"
          git lfs track "*.joblib"
          git lfs track "*.task"
          
          # 4. Tambahkan semua file dan buat commit bersih
          git add .
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Clean Deployment to Hugging Face Spaces"
          
          # 5. Force push ke Hugging Face (hanya membawa 1 commit bersih ini)
          git push --force https://fachrysann:${HF_TOKEN}@huggingface.co/spaces/fachrysann/stroke-detect-pro main