name: Test & Deploy to Hugging Face Space

# Script ini akan berjalan otomatis setiap ada "git push" ke branch "main"
on:
  push:
    branches: [ main ]

jobs:
  # ==========================================
  # JOB 1: TESTING (Dijalankan Pertama Kali)
  # ==========================================
  test:
    name: Run Pytest
    runs-on: ubuntu-latest
    
    # Masukkan ENV variables agar test_main.py punya akses API Key & Database
    env:
      API_KEY: ${{ secrets.API_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      SUPABASE_BUCKET_NAME: "stroke_images"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          lfs: true # LFS True agar file model (.joblib/.pt) ikut ditarik saat testing (Happy Path)

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install System Dependencies (FFmpeg & Audio)
        run: |
          sudo apt-get update
          sudo apt-get install -y libsndfile1 ffmpeg

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest httpx

      - name: Run Tests (Pytest)
        run: |
          pytest test_main.py -v


  # ==========================================
  # JOB 2: DEPLOYMENT (Dijalankan JIKA Job 1 Lulus)
  # ==========================================
  sync-to-hub:
    name: Deploy to HF Spaces
    needs: test # PENTING: Syarat agar job ini jalan adalah 'test' harus sukses
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # Penting jika model menggunakan Git LFS di GitHub

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # 1. Hapus riwayat Git lama di runner agar Hugging Face tidak membaca commit yang bermasalah
          rm -rf .git
          
          # 2. Buat riwayat Git baru yang bersih khusus untuk Hugging Face
          git init
          git branch -M main
          
          # 3. Setup Git LFS dan pastikan file model ditaruh di LFS untuk Hugging Face
          git lfs install
          git lfs track "*.pt"
          git lfs track "*.joblib"
          git lfs track "*.task"
          
          # 4. Tambahkan semua file dan buat commit bersih
          git add .
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit -m "Clean Deployment to Hugging Face Spaces"
          
          # 5. Force push ke Hugging Face (hanya membawa 1 commit bersih ini)
          git push --force https://fachrysann:${HF_TOKEN}@huggingface.co/spaces/fachrysann/stroke-detect-pro main